id = "eclat"
name = "Ã‰clat"
version = "0.1.0"
schema_version = 1
authors = ["Akiyama Kohane <i@kept.to>"]
description = "Immersed in peace and a muted colorscheme"
repository = "https://github.com/utakotoba/eclat-zed"
